name: Mostrar Hora do Push
on:
  push:
    branches:
      - main

jobs:
  mostrar_hora:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir hora do push
        run: |
          python -c "import datetime; print(datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC'))"
